### ISSUE TITLE
Renaming videos on-disk seems to break the plugin

### ISSUE THREAD

**Issue by MaVdbussche** [jellyfin/jellyfin-plugin-intros#12]
Good morning !

First of all thank you for creating this plugin, it's really a great and fun way to improve the viewing experience ! I have played with the previous version from dkanada and recently migrated to this fork.

I run Jellyfin using the Docker image from Linuxserver.io, with my library mounted via bind mounts from my Linux (Ubuntu) host.

_**What I did :**_
I installed the plugin the first time and downloaded a whole folder of videos from the community. I mounted them inside the Jellyfin container and everything worked fine. I played a bit with rules and could see the intros when launching a movie.

Then I realized I had a bit too much files, and decided to rename them to make the process easier. (I can't remember if I shut down the container before doing so)
I then figured I would have to restart the container for those file system changes to be visible to the plugin. So I did.
But now every time I click "Load Videos" in the settings, I get a pop-up with an unhelpful [object Response] message. (see logs in attached file)
**_[error.txt](https://github.com/BrianCArnold/jellyfin-plugin-intros/files/11530001/error.txt)_**

**_What I tried :_**
I figure from the error message that the plugin somehow detects that even though I renamed the file, it was in fact already loaded in the past. However I would expect the file to be skipped (or even better replaced) in that case, instead of a blocking error.
So now I want to "empty the memory" of the plugin to start from scratch. But I can't figure out how.
I reinstalled the plugin multiple times;

- deleted the config file in data/plugins/configurations.Jellyfin.Plugin.LocalIntros.xml;

- restarted the server;

- restarted the host machine;

- created a new mount with a completely new file, removed to old mount, and clicked "Load Videos" again;

I still get the same error no matter what. I can't find a way the reset this "memory", and I can't find either where that is stored in the server files. Is there a database table somewhere that persists after plugin uninstallation ?

Not sure what my next step could be at this point except a complete reinstall of Jellyfin, which I would really like to avoid.

**Comment by MaVdbussche** [comment]
Hello @BrianCArnold,
Sadly I still have the same error, and surprisingly I don't see much more logging than previously (I do have the last .99 version)
I can't figure out where those 118 items are located...

```
[14:17:09] [INF] [41] Jellyfin.Plugin.LocalIntros.LocalIntrosController: Found 118 items in library.

[14:17:09] [ERR] [41] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /LocalIntros/LoadIntros.

System.ArgumentException: An item with the same key has already been added. Key: /intros/93e1bd16ce534f638e2e203016ef6f76.Neon_Reflection_Jellyfin_Pre-roll.mp4

   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)

   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)

   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)

   at Jellyfin.Plugin.LocalIntros.LocalIntrosController.PopulateIntroLibrary()

   at Jellyfin.Plugin.LocalIntros.LocalIntrosController.LoadIntros()

   at lambda_method718(Closure , Object , Object[] )

   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)

   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)

   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)

   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)

   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)

   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)

   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)

   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)

   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)

   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)

   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```
